version: "3.8"

services:
  app:
    image: ${APP_NAME}:latest
    env_file:
      - .env
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
        POETRY_VERSION: ${POETRY_VERSION}
        PYTHON_IMAGE: ${PYTHON_IMAGE}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT}/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"