version: "3"

services:
  app:
    image: ${APP_NAME}:latest
    environment:
      - APP_NAME=${APP_NAME}
      - VENV_PATH=${VENV_PATH}
      - HOST=${HOST}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
  db:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "tiny"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"